replicaCount: 1


image:
  repository: saijalchauhan/swiss
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

opa:
  image:
    repository: openpolicyagent/opa
    tag: edge-rootless
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8181
