replicaCount: 1


image:
  repository: saijalchauhan/swiss:v1
  pullPolicy: IfNotPresent

service:
  port: 8000

opa:
  image:
    repository: openpolicyagent/opa:edge-rootless
    pullPolicy: IfNotPresent
