apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-opa-policies
data:
  policy.rego: |
    package usermanage.authz

    default allow = false

    allow {
        input.role = "admin"
        input.action = "create"
    }

    allow {
        input.role = "admin"
        input.action = "read"
    }

    allow {
        input.role = "user"
        input.action = "read"
    }

  OPA_URL: "http://opa:8181/v1/data/usermanage/authz"
