apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-opa-policies
data:
  policy.rego: |
    package usermanage.authz

    default allow = false

    allow {
        input.auth_header = "Bearer admin_token"
        input.action = "create"
    }

    allow {
        input.auth_header = "Bearer admin_token"
        input.action = "read"
    }

    allow {
        input.auth_header = "Bearer user_token"
        input.action = "read"
    }

  OPA_URL: "http://localhost:8181/v1/data/usermanage/authz"
