apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-user-tokens
type: Opaque
data:
  admin_token: YWRtaW5fdG9rZW4=  # base64 encoded value of "admin_token"
  user_token: dXNlcl90b2tlbg==    # base64 encoded value of "user_token"
