apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-user-tokens
type: Opaque
data:
  ADMIN_TOKEN: YWRtaW4=  # base64 encoded value of "admin_token"
  USER_TOKEN: dXNlcg==    # base64 encoded value of "user_token"
